config/routes.rb
Rails.application.routes.draw do
  resources :user, only: [:show, :create]
  resources :gossip do
    resources :comment, shallow: true
  end
  resources :city, only: [:show]
  root 'gossip#index'
  get 'welcome/:first_name', to: 'welcome#show'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'
  post '/gossip/:id', to: 'comment#create', as: :create_c
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum:14}
  validates :content, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :join_table_gossip_tags
  has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = all_gossips
  end

  private

  def all_gossips
    @city = City.find(params[:id])
    users = @city.users
    gossips = []
    users.each do |user|
     gossips << user.gossips
    end
    return gossips.flatten
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
  end

  def new
    
  end
  
  def create
    @gossip = Gossip.new('user_id' => 11, 'title' => params[:title],'content' => params[:content])
    if @gossip.save
      @gossips = Gossip.all
      render "index" 
    else
      render "new" 
    end    
  end

  def index
    @gossips = Gossip.all
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end
  
  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(update_params)
      @gossips = Gossip.all
      render "index" 
    else
      render "edit"
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossip_index_path
  end

  def shallow
    @comment = @comment.new(shallow: true)
    yield
  ensure
    @comment = @comment.parent
  end

  private

  def update_params
    params.require(:gossip).permit(:title, :content)
  end


  
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<div>
<h2 class="text-center">🏬 <%= @city.name %></h2>
<p class="text-center font-italic">Code Postal: <%= @city.zip_code %></p>
</div>


<div class="row row-cols-1 row-cols-md-4 g-4 px-4">
  <% @gossips.each do |gossip| %>
    <div class="col p-5 d-flex justify-content-center">
      <div class="card" style="width: 40rem; box-shadow: rgba(0, 0, 0, 0.1) -4px 9px 25px -6px; background-color: #f8f8f3">
        <img src="https://i.imgur.com/U4bK2H1.png" class="card-img-top opac_img" alt="message_bottle">
        <div class="card-body d-flex flex-column justify-content-between">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Auteur(e) : <%= gossip.user.first_name%></p>
          <%= link_to "Afficher le potin", gossip_path(gossip.id), class: "btn btn-secondary d-flex justify-content-center align-items-end"%>
        </div>        
      </div>
    </div>
  <% end %>
</div>

app/views/gossip/edit.html.erb
<% begin %>
<% if @gossip.errors.any? %>
    <div class="alert alert-danger w-100" role="alert">
  <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  🤬 Le jour où les cons auront du flair, toi, tu vas trouver des truffes !!! 🤬
  </div>
<% end %>
<%rescue => e %>
<%end%>
<div>
</div>
<div class="d-flex align-items-center flex-column">
  <h1>Modifiez votre potin ici :</h1>
  <p class="rules">Quelques règles:</p>
  <ul class="rules_list">
    <li>Titre obligatoire</li>
    <li>Titre entre 3 et 14 caractères</li>
    <li>Le contenu ne doit pas être vide</li>
  </ul>

  <%= form_for @gossip do |f| %>
    
    <div class="form-group", style="width: 500px">
      <label>Titre du potin</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group", style="width: 500px">
      <label>Contenu du potin</label>
      <%= f.text_area :content, class:"form-control"%>
    </div>

    <div class="form-group">
      <button type="submit", class= "btn btn-warning mb-5 mt-5" >Modifier le potin</button>
    </div>


  <% end %>

</div>
<div>
</div>

app/views/gossip/index.html.erb
<% begin %>
<% unless @gossip.errors.any? %>
  <div class="alert alert-success w-100" role="alert">
  <p>Votre potin a été ajouté/modifié avec succès</p>
  </div>
<% end %>
<%rescue => e %>
<%end%>

<img src="https://i.imgur.com/OVqr7zI.jpg" class="img-fluid">
<div class="home_welcome text-center">
  <h1 class= "text-center display-1" style="padding-bottom: 50px">Bienvenue à toi jeune pirate</h1>
  <%= link_to "Cliques ici pour créer ton gossip", new_gossip_path, class: "btn btn-warning d-inline-flex justify-content-center p-3"%>
</div>

<h4 style="padding-top: 40px; padding-left: 40px; text-decoration: underline" >Voici la liste complète des potins:</h4>

<div class="row row-cols-1 row-cols-md-4 g-4 px-4">
  <% @gossips.each do |gossip| %>
  <div class="col p-5 d-flex justify-content-center">
    <div class="card" style="width: 40rem; box-shadow: rgba(0, 0, 0, 0.1) -4px 9px 25px -6px; background-color: #f8f8f3">
      <img src="https://i.imgur.com/U4bK2H1.png" class="card-img-top opac_img" alt="message_bottle">
        <div class="card-body d-flex flex-column justify-content-between">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Auteur(e) : <%= gossip.user.first_name%></p>
          <p class="card-text">Coms : <%= gossip.comments.length%>
          <%= link_to "Afficher le potin", gossip_path(gossip.id), class: "btn btn-secondary d-flex justify-content-center align-items-end"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossip/new.html.erb
<div>
<% begin %>
<% if @gossip.errors.any? %>
    <div class="alert alert-danger w-100" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  🤬 Le jour où les cons auront du flair, toi, tu vas trouver des truffes !!! 🤬
  </div>
<% end %>
<%rescue => e %>
<%end%>
</div>
<div class="d-flex align-items-center flex-column">
    <h1>Publiez votre potin ici :</h1>
    <p class="rules">Quelques règles:</p>
    <ul class="rules_list">
        <li>Titre obligatoire</li>
        <li>Titre entre 3 et 14 caractères</li>
        <li>Le contenu ne doit pas être vide</li>
    </ul>
    <div>
        <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
        <%= label_tag :Titre %>
    </div>
    <div class="form-group", style="width: 500px">
        <%= text_field_tag :title, "", class:"form-control" %>
        <br /> <br />
    </div>
    <div>
        <%= label_tag :Contenu %>
    </div>
    <div class="form-group", style="width: 500px">
        <%= text_area_tag :content, "", class:"form-control" %>
        <br /> <br />
    </div>
    <div>
        <%= submit_tag 'Publier', class:"btn btn-warning mb-5"%>
    </div>
        <% end %>
    </div>
</div>
<div>
</div>

app/views/gossip/show.html.erb
<div>
</div>
<div class="grid text-center">
  <div class="row row-cols-1 row-cols-md-2 g-4 d-flex align-items-center">
    <div class="g-col-5">
      <h3 class="p-3">Des précisions à propos de ce potin ?</h3>
      <h4 class="p-3">Titre: <%= @gossip.title%></h4>
      <h5 class="p-3">Auteur: <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id), class:"author"%></h5>
      <p class="city_name p-3">Ville: <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %></p>
      <blockquote class="blockquote">
        <p class="mb-0">Contenu: <%= @gossip.content%></p>
      </blockquote>
      <p class="p-3">Créé le: <%= @gossip.created_at.strftime("%d/%m/%Y à %Hh%M")%></p>
      <div class="d-flex justify-content-evenly"> 
        <div>
          <%= link_to "Modifier", edit_gossip_path(@gossip.id), class: "btn btn-warning d-inline-flex justify-content-center p-3"%>
        </div>
        <div>
          <%= link_to "Supprimer", gossip_path(@gossip.id), class: "btn btn-danger d-inline-flex justify-content-center p-3", :data => {:confirm => 'Are you sure?', :method => "DELETE"} %>
        </div>
      </div>
    </div>
    
    <div class="g-col-5">
      <img src="https://i.imgur.com/WFzrYz9.jpg" style="width: 80%"> 
    </div>
  </div>
</div>
<div>
  <h3>section commentaires:<h3>
  <div class="row row-cols-1 row-cols-md-2 g-4 d-flex align-items-center justify-content-around">
    <div class="g-col-5">
      <% @comments.each do |comment| %>
        <div class="row comment">
          <div class="col-sm-3">
            <div class="comment_author">
              <p><%=comment.user.first_name%> <%=comment.user.last_name%> : <%= link_to "📑", edit_comment_path(comment.id) %></p>
            </div>
          </div>
          <div class="g-col-5">
            <div class="well">
              <p><%=comment.content%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-4">
      <%= form_for :comment do |f| %>
        
        <div class="form-group", style="width: 500px">
        <h3>Ecrire un commentaire: </h3>
          <%= f.text_area :content, class:"form-control"%>
        </div>

        <div class="form-group d-flex justify-content-end" , style="width: 500px">
          <button type="submit", class= "btn btn-warning mb-3 mt-3", data_method= "create" >Commenter</button>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/user/show.html.erb
<div>
</div>
<div class="grid text-center">
  <div class="row row-cols-1 row-cols-md-2 g-4 d-flex align-items-center">
    <div class="g-col-5">
        <img src="https://i.imgur.com/VoLdiML.jpg" style="width: 80%">
    </div>
    <div class="g-col-5">
        <h1 class="p-3" style="color: rgb(110, 76, 7)">Fiche de l'auteur:</h1>
        <h2 class="p-3"><%= "#{@user.first_name} #{@user.last_name}, #{@user.age} ans" %></h2>
        <p class="p-3">description: <%= @user.description %></p>
        <p class="p-3"><%= "email: #{@user.email}"%></p>
        <p class="city_name p-3">Ville: <%= link_to "#{@user.city.name}", city_path(@user.city.id) %></p>
    </div>
  </div>
</div>